-- Generated from Data/Land's_End_Civilization.xml
-- Civilization identity, city/citizen names, trait ownership and civilization modifiers.
-- Do not add idempotent DELETE statements here: Civ VI XML <Row> semantics are INSERT-only.

-- Registers an identifier and its engine kind before domain rows use it.
INSERT INTO Types
    (Type, Kind)
VALUES
    ('CIVILIZATION_LAND_S_END', 'KIND_CIVILIZATION'),
    ('TRAIT_CIVILIZATION_LAND_S_END', 'KIND_TRAIT');

INSERT INTO Civilizations
    (CivilizationType, Name, Description, Adjective, RandomCityNameDepth, StartingCivilizationLevelType, Ethnicity)
VALUES
    ('CIVILIZATION_LAND_S_END', 'LOC_CIVILIZATION_LAND_S_END_NAME', 'LOC_CIVILIZATION_LAND_S_END_DESCRIPTION', 'LOC_CIVILIZATION_LAND_S_END_ADJECTIVE', 1, 'CIVILIZATION_LEVEL_FULL_CIV', 'ETHNICITY_EURO');

-- Many-to-many bridge between Civilizations and Leaders.
INSERT INTO CivilizationLeaders
    (CivilizationType, LeaderType, CapitalName)
VALUES
    ('CIVILIZATION_LAND_S_END', 'LEADER_LILY', 'LOC_CITY_NAME_WHITE_PARISH');

INSERT INTO Traits
    (TraitType, Name, Description)
VALUES
    ('TRAIT_CIVILIZATION_LAND_S_END', 'LOC_TRAIT_CIVILIZATION_LAND_S_END_NAME', 'LOC_TRAIT_CIVILIZATION_LAND_S_END_DESCRIPTION');

-- Attaches civilization, district and building traits to the civilization.
INSERT INTO CivilizationTraits
    (CivilizationType, TraitType)
VALUES
    ('CIVILIZATION_LAND_S_END', 'TRAIT_CIVILIZATION_LAND_S_END'),
    ('CIVILIZATION_LAND_S_END', 'TRAIT_DISTRICT_WHITE_HOLY_SITE'),
    ('CIVILIZATION_LAND_S_END', 'TRAIT_BUILDING_WHITE_PRUESTESS_STATUE');

INSERT INTO CityNames
    (CivilizationType, CityName)
VALUES
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_WHITE_PARISH'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_CLIFFSIDE_HAMLET'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_WITCH_S_THICKET'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_CATACOMBS'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_TWIN_SPIRES'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_RUINED_CASTLE'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_STOCKADE'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_VERBOTEN_DOMAIN'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_ABYSS'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_LAND_S_EDGE'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_BLIGHTED_HEART'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_CELLAR'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_CATHEDRAL_CLOISTER'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_SAINT_S_PASSAGE'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_CROSSROADS'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_DRYAD_LAKE'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_COLLAPSED_SHACK'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_BRIDGEHEAD'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_WITCH_S_HERMITAGE'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITY_NAME_COVEN_HALLS');

INSERT INTO CivilizationCitizenNames
    (CivilizationType, CitizenName, Female)
VALUES
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_SIEGRID', 1),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_SILVA', 1),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_ELEINE', 1);

INSERT INTO CivilizationCitizenNames
    (CivilizationType, CitizenName)
VALUES
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_GERROD'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_JULIUS'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_ULV'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_HOENIR'),
    ('CIVILIZATION_LAND_S_END', 'LOC_CITIZEN_NAME_FADEN');

INSERT INTO StartBiasResources
    (CivilizationType, ResourceType, Tier)
VALUES
    ('CIVILIZATION_LAND_S_END', 'RESOURCE_IRON', 2);

-- Bridge: a Trait owns one or more Modifiers.
INSERT INTO TraitModifiers
    (TraitType, ModifierId)
VALUES
    ('TRAIT_CIVILIZATION_LAND_S_END', 'MODIFIER_LAND_S_END_UNITS_STRENGTH_REDUCTION_FOR_DAMAGE'),
    ('TRAIT_CIVILIZATION_LAND_S_END', 'MODIFIER_LAND_S_END_CAPTURED_CITY_EUREKA'),
    ('TRAIT_CIVILIZATION_LAND_S_END', 'MODIFIER_LAND_S_END_CAPTURED_CITY_INSPIRATION');

-- Defines an effect and optionally points to a RequirementSet.
INSERT INTO Modifiers
    (ModifierId, ModifierType)
VALUES
    ('MODIFIER_LAND_S_END_UNITS_STRENGTH_REDUCTION_FOR_DAMAGE', 'MODIFIER_PLAYER_UNITS_ADJUST_STRENGTH_REDUCTION_FOR_DAMAGE_MODIFIER'),
    ('MODIFIER_LAND_S_END_CAPTURED_CITY_EUREKA', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER'),
    ('MODIFIER_LAND_S_END_CAPTURED_CITY_INSPIRATION', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER');

INSERT INTO Modifiers
    (ModifierId, ModifierType, Permanent, RunOnce)
VALUES
    ('MODIFIER_LAND_S_END_EUREKA', 'MODIFIER_PLAYER_GRANT_RANDOM_TECHNOLOGY_BOOST_GOODY_HUT', 1, 1),
    ('MODIFIER_LAND_S_END_INSPIRATION', 'MODIFIER_PLAYER_GRANT_RANDOM_CIVIC_BOOST_GOODY_HUT', 1, 1);

-- Key/value parameters consumed by each ModifierType.
INSERT INTO ModifierArguments
    (ModifierId, Name, Value)
VALUES
    ('MODIFIER_LAND_S_END_UNITS_STRENGTH_REDUCTION_FOR_DAMAGE', 'Amount', '100'),
    ('MODIFIER_LAND_S_END_CAPTURED_CITY_EUREKA', 'ModifierId', 'MODIFIER_LAND_S_END_EUREKA'),
    ('MODIFIER_LAND_S_END_EUREKA', 'Amount', '1'),
    ('MODIFIER_LAND_S_END_EUREKA', 'Source', 'CAPTURED_CITY'),
    ('MODIFIER_LAND_S_END_CAPTURED_CITY_INSPIRATION', 'ModifierId', 'MODIFIER_LAND_S_END_INSPIRATION'),
    ('MODIFIER_LAND_S_END_INSPIRATION', 'Amount', '1'),
    ('MODIFIER_LAND_S_END_INSPIRATION', 'Source', 'CAPTURED_CITY');
