-- Generated from Data/Land's_End_Building.xml
-- Unique building, yields/prerequisites and city/district requirement chains.
-- Do not add idempotent DELETE statements here: Civ VI XML <Row> semantics are INSERT-only.

-- Registers an identifier and its engine kind before domain rows use it.
INSERT INTO Types
    (Type, Kind)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'KIND_BUILDING'),
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'KIND_TRAIT');

INSERT INTO Traits
    (TraitType, Name, Description)
VALUES
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'LOC_TRAIT_BUILDING_WHITE_PRUESTESS_STATUE_NAME', 'LOC_TRAIT_BUILDING_WHITE_PRUESTESS_STATUE_DESCRIPTION');

-- Maps the civilization-unique building to the base building it replaces.
INSERT INTO BuildingReplaces
    (CivUniqueBuildingType, ReplacesBuildingType)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'BUILDING_TEMPLE');

INSERT INTO Buildings
    (BuildingType, Name, Description, TraitType, PrereqCivic, PrereqDistrict, PurchaseYield, Cost, AdvisorType, Maintenance, CitizenSlots)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'LOC_BUILDING_WHITE_PRUESTESS_STATUE_NAME', 'LOC_BUILDING_WHITE_PRUESTESS_STATUE_DESCRIPTION', 'TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'CIVIC_THEOLOGY', 'DISTRICT_HOLY_SITE', 'YIELD_GOLD', 120, 'ADVISOR_RELIGIOUS', 2, 1);

INSERT INTO BuildingPrereqs
    (Building, PrereqBuilding)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'BUILDING_SHRINE');

INSERT INTO Building_YieldChanges
    (BuildingType, YieldType, YieldChange)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'YIELD_SCIENCE', 2),
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'YIELD_FAITH', 2),
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'YIELD_GOLD', 2),
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'YIELD_FOOD', 2),
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'YIELD_PRODUCTION', 2),
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'YIELD_CULTURE', 2);

INSERT INTO Building_GreatPersonPoints
    (BuildingType, GreatPersonClassType, PointsPerTurn)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'GREAT_PERSON_CLASS_PROPHET', 1);

INSERT INTO Building_GreatWorks
    (BuildingType, GreatWorkSlotType, NumSlots)
VALUES
    ('BUILDING_WHITE_PRUESTESS_STATUE', 'GREATWORKSLOT_RELIC', 1);

INSERT INTO Unit_BuildingPrereqs
    (Unit, PrereqBuilding)
VALUES
    ('UNIT_APOSTLE', 'BUILDING_WHITE_PRUESTESS_STATUE'),
    ('UNIT_INQUISITOR', 'BUILDING_WHITE_PRUESTESS_STATUE'),
    ('UNIT_WARRIOR_MONK', 'BUILDING_WHITE_PRUESTESS_STATUE'),
    ('UNIT_GURU', 'BUILDING_WHITE_PRUESTESS_STATUE');

-- Bridge: a Trait owns one or more Modifiers.
INSERT INTO TraitModifiers
    (TraitType, ModifierId)
VALUES
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_SCIENCE'),
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_CULTURE'),
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_PRODUCTION'),
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD'),
    ('TRAIT_BUILDING_WHITE_PRUESTESS_STATUE', 'MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD_H');

-- Defines an effect and optionally points to a RequirementSet.
INSERT INTO Modifiers
    (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_SCIENCE', 'MODIFIER_ALL_CITIES_ADJUST_CITY_YIELD_CHANGE', 'REQSET_LE_CITY_HAS_CAMPUS'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_CULTURE', 'MODIFIER_ALL_CITIES_ADJUST_CITY_YIELD_CHANGE', 'REQSET_LE_CITY_HAS_THEATER'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_PRODUCTION', 'MODIFIER_ALL_CITIES_ADJUST_CITY_YIELD_CHANGE', 'REQSET_LE_CITY_HAS_INDUSTRIAL_ZONE'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD', 'MODIFIER_ALL_CITIES_ADJUST_CITY_YIELD_CHANGE', 'REQSET_LE_CITY_HAS_COMMERCIAL_HUB'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD_H', 'MODIFIER_ALL_CITIES_ADJUST_CITY_YIELD_CHANGE', 'REQSET_LE_CITY_HAS_HARBOR');

-- Key/value parameters consumed by each ModifierType.
INSERT INTO ModifierArguments
    (ModifierId, Name, Value)
VALUES
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_SCIENCE', 'Amount', '2'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_CULTURE', 'Amount', '2'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_PRODUCTION', 'Amount', '2'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD', 'Amount', '2'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD_H', 'Amount', '2'),
    ('MODIFIER_WHITE_PRUESTESS_STATUE_YIELD_GOLD_H', 'YieldType', 'YIELD_GOLD');

-- Defines how member requirements are evaluated (for example TEST_ALL).
INSERT INTO RequirementSets
    (RequirementSetId, RequirementSetType)
VALUES
    ('REQSET_LE_CITY_HAS_CAMPUS', 'REQUIREMENTSET_TEST_ALL'),
    ('REQSET_LE_CITY_HAS_THEATER', 'REQUIREMENTSET_TEST_ALL'),
    ('REQSET_LE_CITY_HAS_INDUSTRIAL_ZONE', 'REQUIREMENTSET_TEST_ALL'),
    ('REQSET_LE_CITY_HAS_COMMERCIAL_HUB', 'REQUIREMENTSET_TEST_ALL'),
    ('REQSET_LE_CITY_HAS_HARBOR', 'REQUIREMENTSET_TEST_ALL');

-- Bridge between RequirementSets and Requirements.
INSERT INTO RequirementSetRequirements
    (RequirementSetId, RequirementId)
VALUES
    ('REQSET_LE_CITY_HAS_CAMPUS', 'REQ_LE_CITY_HAS_BUILDING'),
    ('REQSET_LE_CITY_HAS_CAMPUS', 'REQ_LE_CITY_HAS_CAMPUS'),
    ('REQSET_LE_CITY_HAS_THEATER', 'REQ_LE_CITY_HAS_BUILDING'),
    ('REQSET_LE_CITY_HAS_THEATER', 'REQ_LE_CITY_HAS_THEATER'),
    ('REQSET_LE_CITY_HAS_INDUSTRIAL_ZONE', 'REQ_LE_CITY_HAS_BUILDING'),
    ('REQSET_LE_CITY_HAS_INDUSTRIAL_ZONE', 'REQ_LE_CITY_HAS_INDUSTRIAL_ZONE'),
    ('REQSET_LE_CITY_HAS_COMMERCIAL_HUB', 'REQ_LE_CITY_HAS_BUILDING'),
    ('REQSET_LE_CITY_HAS_COMMERCIAL_HUB', 'REQ_LE_CITY_HAS_COMMERCIAL_HUB'),
    ('REQSET_LE_CITY_HAS_HARBOR', 'REQ_LE_CITY_HAS_BUILDING'),
    ('REQSET_LE_CITY_HAS_HARBOR', 'REQ_LE_CITY_HAS_HAS_HARBOR');

-- Defines one reusable predicate.
INSERT INTO Requirements
    (RequirementId, RequirementType)
VALUES
    ('REQ_LE_CITY_HAS_BUILDING', 'REQUIREMENT_CITY_HAS_BUILDING'),
    ('REQ_LE_CITY_HAS_CAMPUS', 'REQUIREMENT_CITY_HAS_DISTRICT'),
    ('REQ_LE_CITY_HAS_THEATER', 'REQUIREMENT_CITY_HAS_DISTRICT'),
    ('REQ_LE_CITY_HAS_INDUSTRIAL_ZONE', 'REQUIREMENT_CITY_HAS_DISTRICT'),
    ('REQ_LE_CITY_HAS_COMMERCIAL_HUB', 'REQUIREMENT_CITY_HAS_DISTRICT'),
    ('REQ_LE_CITY_HAS_HAS_HARBOR', 'REQUIREMENT_CITY_HAS_DISTRICT');

-- Key/value parameters for each requirement predicate.
INSERT INTO RequirementArguments
    (RequirementId, Name, Value)
VALUES
    ('REQ_LE_CITY_HAS_BUILDING', 'BuildingType', 'BUILDING_WHITE_PRUESTESS_STATUE'),
    ('REQ_LE_CITY_HAS_CAMPUS', 'DistrictType', 'DISTRICT_CAMPUS'),
    ('REQ_LE_CITY_HAS_THEATER', 'DistrictType', 'DISTRICT_THEATER'),
    ('REQ_LE_CITY_HAS_INDUSTRIAL_ZONE', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE'),
    ('REQ_LE_CITY_HAS_COMMERCIAL_HUB', 'DistrictType', 'DISTRICT_COMMERCIAL_HUB'),
    ('REQ_LE_CITY_HAS_HAS_HARBOR', 'DistrictType', 'DISTRICT_HARBOR');
